version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: innosecportal-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: innosecportal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - innosecportal-network

  redis:
    image: redis:7-alpine
    container_name: innosecportal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - innosecportal-network

volumes:
  postgres-data:
  redis-data:

networks:
  innosecportal-network:
    driver: bridge 